# Generated by Django 4.2 on 2023-07-21 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=1500)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 7, 21, 21, 34, 14, 810606, tzinfo=datetime.timezone.utc))),
                ('draft', models.BooleanField(default=True)),
            ],
        ),
    ]
